---
- name: Install required packages for NFS
  apt:
    name: "{{ _nfs_apt_packages | flatten }}"
    state: present
    cache_valid_time: 3600
    update_cache: yes
  vars:
    _nfs_apt_packages:
      - nfs-common
      - "{{'nfs-kernel-server' if nfs_exports else [] }}"
