---
# tasks file for lae.nfs
- name: Gather OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version }}.yml"
    - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version }}.yml"
    - "{{ ansible_distribution|lower }}.yml"
    - "{{ ansible_os_family|lower }}.yml"

- include: validate_variables.yml
- include: "install_packages_{{ ansible_pkg_mgr }}.yml"

- import_tasks: server.yml
  when: nfs_exports

- import_tasks: client.yml
  when: nfs_mounts
